# -*- coding: utf-8 -*-
"""NLTK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJ5fj2svFLWncQg3z_-lKW3fDKVh5rtp
"""

import nltk

text="Once there was a black cat and a brown dog. The cat chased the mouse around the house. My neighbor has a fat cat that sleeps all day. The wild dog barked at the sneaky cat. Look at that quick cat jump over the lazy dog. The pet dog ran after the small cat. Every night the cat and dog shared their food bowl."

text

tokens=text.split()

from nltk import Text
story=Text(tokens)

story

story.concordance("cat")

print(story.common_contexts(['dog','cat']))

story.dispersion_plot(["cat","dog"])

story.generate()

story1='''The brave black cat and the loyal brown dog were best friends who lived in a big green house by the river. Every morning the cat climbed the tall tree while the dog chased rabbits through the tall grass. One day they found a shiny gold key hidden under an old oak tree near the sparkling blue river. The curious cat picked up the key in her mouth and the excited dog barked loudly to call their friend the wise old owl.

The owl told them the key opened a secret cave behind the roaring waterfall where lost treasure waited. So the brave cat and loyal dog set off on their big adventure through the dark forest. They crossed the rickety wooden bridge over the rushing river and climbed the steep rocky mountain. Along the way they met a sneaky fox who tried to steal their shiny gold key but the smart cat tricked him with a fake key made from a yellow leaf.

Finally they reached the roaring waterfall and found the secret cave entrance. Inside the dark cave sparkled piles of gold coins and precious jewels guarded by a sleeping dragon. The quiet cat tiptoed past the dragon while the strong dog pushed away heavy rocks blocking the treasure chest. Together they unlocked the big chest with their shiny gold key and found ancient maps showing even greater treasure across the seven seas.

Suddenly the dragon woke up angry and breathed fire but the quick cat jumped on his back and the brave dog pulled his tail. They escaped with their treasure just as the cave collapsed behind them. Back home they shared their gold coins with all the forest animals and built a new school where young cats and dogs could learn adventure skills. From that day forward every cat and dog in the valley dreamed of finding their own secret treasure and lived happily ever after.

The end.
'''

story1

tokens=story1.split()

story1=Text(tokens)



story1.concordance("cat")

print(story1.common_contexts(['dog']))

story1.similar("dog")

story1.generate

len(story1)

len(set(story1))  #unique words

sorted(set(story1))

story1.count('cat')

