select * from consumables;
alter table consumables modify column color varchar(20);
select partNumber,color,consumableType from consumables;
select * from consumables where color='black';
select * from consumables where listPrice>50;
select * from consumables order by listPrice desc;
select * from consumables order by listPrice desc limit 5;
select * from consumables where streetPrice is Null;
select count(_id) from consumables;
select min(listPrice) minimum,max(listPrice) maximum from consumables;
select consumableType,count(_id) from consumables group by consumableType;
select consumableType,sum(blackLifePages) from consumables group by consumableType;
select tcoCategory,avg(listPrice) from consumables group by tcoCategory;
select * from consumables where listPrice between 30 and 100;
select * from consumables where partNumber like 'DR%';
select * from consumables where blackLifePages>0 and colorLifePages>0;
select * from consumables where colorLifePages is null or colorLifePages=0;
select tcocategory,count(_id) from consumables 	group by tcocategory having tcocategory!='TCO_LLC';
select * from consumables where listprice=(select max(listPrice) from consumables);
select guid,count(_id) as a from consumables group by guid;
SELECT partNumber,consumableType,listPrice,RANK() OVER (ORDER BY listPrice DESC) AS price_rank FROM consumables;
select consumableType,listprice from consumables group by consumableType order by listprice desc limit 3;