# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bnU8JQeED3d0zkJBv-kFolzMFtrLlkR
"""

import re

chat1 = "student: my phone number is 9876543210 😊 email is student123@gmail.com"
chat2 = "teacher: contact me at (080)-23456789, mail: teacher@school.edu"
chat3 = "admin: helpline 123-456-7890 email admin@college.in"

pattern='[a-z0-9]*@[a-z0-9]*\.com'
matches=re.findall(pattern,chat1)
matches

text="""Ambani in 2007
Born	19 April 1957 (age 68)
Aden, Aden Colony
(now Yemen)[1][2]
Alma mater
St. Xavier's College, Mumbai
Institute of Chemical Technology (B.E.)
Occupation	Businessman
Years active	1981–present
Organization	Reliance Industries
Title	Chairman and MD of Reliance Industries[3]
Spouse	Nita Dalal ​(m. 1985)​[4]
Children	3
Parents
Dhirubhai Ambani (father)
Kokilaben Ambani (mother)
Relatives	Anil Ambani (brother)
Tina Ambani (sister-in-law)"""

pattern='Born(.*)\(age'
matches=re.findall(pattern,text)
matches

born=matches[0].strip()
born

pattern='Mumbai\n(.*)\('
matches=re.findall(pattern,text)
matches

def pattern_matching(pattern,text):
  matches=re.findall(pattern,text)
  return matches[0].strip

age=pattern_matching('age.*(\d{2})',text)
age=int(age[0])
age

occupation=pattern_matching('Occupation(.*)',text)

occupation=occupation[0].strip()

Organization=pattern_matching('Organization(.*)',text)

Organization=Organization[0].strip()

Organization

