# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyyeN088dgYKqgBzNy_9SYsQGcSc3qiS
"""

mail="""From: Dr. Meera Sharma <meera.sharma@iisc.ac.in>
To: Rahul Verma <rahul.verma99@gmail.com>, Aisha Khan <aisha.khan@delhiuniv.edu>
CC: support@helpdesk.io
Date: January 12, 2025 09:30 AM
Subject: AI Lecture Follow-up & Research Opportunity

Hello Rahul and Aisha,

Thanks for attending the session at the Indian Institute of Science, Bangalore.
Please submit your draft by March 2025. The lecture video link is:
https://www.iisc.ac.in/events/ai-lecture-2025?ref=mail

Your registration IDs are:
REG-2025-00123
REG-2025-00124

We also received the payment confirmation:
Receipt: RCP-889912
Amount: ₹15000
Extra donation: $45,000
Grant adjustment: €3,500

Important Dates:
- 12/05/2025 (document submission deadline)
- 31-12-2025 (final review)
- March 2025 (progress check)
- January 2025 (event month)

Phone contacts:
+91-98765-43210
202.555.0198
+1 202-555-0173

Addresses:
Office: 4th Floor, Block B, MG Road, Bangalore - 560001
Lab: Room 12A, IISc Campus, Bengaluru 560012

System Logs:
[2025-01-12 09:31:05] INFO  User login: rahul.verma99@gmail.com IP=192.168.1.10
[2025-01-12 09:35:42] WARN  Payment pending: INV-2025-002 Amount=₹15000
[2025-01-12 09:40:00] ERROR Failed API call to http://backup.company.net/api/v1/status code=503
[2025-01-12 10:01:17] INFO  Token issued: TRK1234567
[2025-01-12 10:05:22] INFO  Token issued: TRK7654321

Ticket History:
TCK-77881 opened on 2025/01/10 by user aisha.khan@delhiuniv.edu
TCK-77882 closed on 2025-01-11 by admin@company.org

Notes:
Meeting duration: 3 years (research timeline)
Training period: 12 months
Final minutes were critical for Q&A.
Call scheduled at 07:30 PM tomorrow.

Regards,
Admin Team
"""

import re
def find(pattern,text):
  a=re.findall(pattern,text)
  return a

pattern='[\<\w\.\d*\-\_]+@[\>\w\.\d*\-\_]+'
a=find(pattern,mail)
print(f"The extracted phone number are:{a}")

pattern="\+?\d{0,2}-\d{5}-\d{5}|\+?\.?\d{0,2}.?\d{3}.\d{3}.\d{4}"
a=find(pattern,mail)
print(f"The extracted phone number are:{a}")

pattern=r"\bhttps?.*"
a=find(pattern,mail)
print(f"The extracted urls are:{a}")

pattern=r"[₹$€]+.*"
a=find(pattern,mail)
print(f"The extracted money are:{a}")

pattern=r"\bREG.*"
a=find(pattern,mail)
print(f"The extracted REG are:{a}")

pattern=r'\d{4}-\d{2}-\d{2}.\d{2}:\d{2}:\d{2}'
a=find(pattern,mail)
print(f"The extracted INV are:{a}")

pattern=r'\bERROR.*'
a=find(pattern,mail)
print(f"The extracted errors are:{a}")

pattern=r'[a-zA-Z0-9/]+.\d{2}..\d{4}'
a=find(pattern,mail)
print(f"The extracted errors are:{a}")
